### ISSUE TITLE
Upgrade to thumbor 7

### ISSUE THREAD

**Issue by heynemann** [dffrntmedia/thumbor-request-modifier-http-loader#1]
Hey great project! Do you think we can work together to upgrade this to thumbor 7 and python 3? Would be an awesome addition to thumbor's community.

Great job anyways! I'm adding this to awesome thumbor!

**Comment by mbarouski** [comment]
Hey @heynemann 👋🏻 
The project is upgraded to move on Thumbor 7 and Python 3 🎉 
So, closing the issue... ✅ 

And thanks for mentioning us in awesome thumbor :)
